- hosts: srv1
  become: no
  #gather_facts: yes
  tasks:
  - name: Ping host srv1
    ansible.builtin.ping:

  - name: print message
    ansible.builtin.debug:
      msg: server unbuntu-srv1 is available

  - name: copy local source code to srv1
    copy:
      src: ../../docker/compose/primary
      dest: ./db_cluster
      remote_src: no

  - name: shut down the primary server of db cluster on srv1 using Docker Compose
    docker_compose:
      project_src: ./db_cluster/primary
      files:
      - docker-compose.yaml
      pull: no
      state: absent

