apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql
  labels:
    app: postgresql
    app.kubernetes.io/name: postgresql
data:
  init-primary.sql: |
    /* 
      init scipt that is run at the startup of the primary instance.
    */
    CREATE USER replicator WITH REPLICATION ENCRYPTED PASSWORD 'replicator';
    SELECT pg_create_physical_replication_slot('replication_slot');




